# Generated by Django 3.2.9 on 2022-03-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu',
            new_name='stuEmail',
        ),
    ]
