# Generated by Django 3.2.9 on 2022-03-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_stu_student_stuemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bran',
            field=models.CharField(default='', max_length=5),
        ),
    ]
